### ISSUE TITLE
Support custom responses

### ISSUE THREAD

**Issue by SoniEx2** [lexi-the-cute/block-meta-from-fedi#1]
The current blocking approach drops connections altogether. This doesn't feel like the most appropriate blocking strategy. With custom responses, it would be possible to return, say, a profile that says "Your instance has been blocked for TOS", as well as posts that say "Your instance has been blocked for TOS". This would be much more effective as a long-term blocking strategy because it doesn't hide your own instance's existence from their end-users, while still providing 100% privacy protection as none of the responses are "real".

Tho our biggest concern is the federation of mentions from instances that refuse to block them. Unfortunately there's no real way to solve that.

**Comment by lexi-the-cute** [comment]
I can definitely take a look into making that an option as part of the same addition as the fake data addition. The code would be redirecting to a custom web server which is different than the main server.

**Comment by lexi-the-cute** [comment]
Now you can redirect Facebook packets to a custom web server to handle as you please! An example command is below.

```bash
# DNAT is required for redirection.
# :8081 is the destination port you want to redirect to
# You can use my-public-ip:my-public-port. As long as the port can be accessed from the outside
python3 main.py -p DNAT -d ":8081"
```
