### ISSUE TITLE
don’t use M$ GutHub

### ISSUE THREAD

**Issue by jwmh** [lexi-the-cute/block-meta-from-fedi#2]
Love this!
but/and
use Codeberg / Forgejo
please

**Comment by lexi-the-cute** [comment]
I'll definitely take a look into it. If I do migrate, it might take a while as I have projects which rely on Github services to function.

I'm doing research on Codeberg / Forgejo

**Comment by lexi-the-cute** [comment]
I setup a mirror of the repo at https://codeberg.org/alexis/block-meta-from-fedi. Turns out I already had a Codeberg account that I forgot about. I plan on keeping it as a mirror for now, but may eventually make a complete move in the future.
